apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: kafka-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: ghcr.io/precise-charmerr/order-service:${IMAGE_VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: kafka-demo
spec:
  selector:
    app: order-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP